; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 5
; RUN: opt < %s -passes=lightsan -S | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"

define dso_local i32 @main() {
; CHECK-LABEL: define dso_local i32 @main() {
; CHECK-NEXT:    call void @__lightsan_pre_function(ptr @__lightsan_.str, i32 0, ptr null)
; CHECK-NEXT:    ret i32 0
;
  ret i32 0
}

define dso_local i32 @notmain() {
; CHECK-LABEL: define dso_local i32 @notmain() {
; CHECK-NEXT:    ret i32 0
;
  ret i32 0
}
