; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-file=%S/branch_config.json -S | FileCheck %s
define i32 @foo(i1 %c) {
; CHECK-LABEL: define i32 @foo(
; CHECK-SAME: i1 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = zext i1 [[C]] to i8
; CHECK-NEXT:    [[TMP8:%.*]] = call i8 @__instrumentor_pre_br(i8 1, i8 [[TMP0]], i64 2, i32 1) #[[ATTR0:[0-9]+]]
; CHECK-NEXT:    [[TMP9:%.*]] = trunc i8 [[TMP8]] to i1
; CHECK-NEXT:    br i1 [[TMP9]], label %[[A:.*]], label %[[B:.*]]
; CHECK:       [[A]]:
; CHECK-NEXT:    ret i32 0
; CHECK:       [[B]]:
; CHECK-NEXT:    [[TMP3:%.*]] = call i8 @__instrumentor_pre_br(i8 0, i8 1, i64 1, i32 2) #[[ATTR0]]
; CHECK-NEXT:    br label %[[D:.*]]
; CHECK:       [[D]]:
; CHECK-NEXT:    ret i32 1
;
entry:
  br i1 %c, label %a, label %b
a:
  ret i32 0
b:
  br label %d
d:
  ret i32 1
}
